
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 1065;
const int acc_off_y = 348;
const int acc_off_z = -1542;
const float acc_scale_x = 14232.556407;
const float acc_scale_y = 17893.372908;
const float acc_scale_z = 19566.577093;

const int magn_off_x = -160;
const int magn_off_y = -27;
const int magn_off_z = -95;
const float magn_scale_x = 286.532561;
const float magn_scale_y = 262.241216;
const float magn_scale_z = 229.608891;
